name = "env-app"
main = "src/index.ts"
compatibility_date = "2023-02-27"

# LOCAL db, kv should be in ~ .wrangler/state
[env.local]
name = "env-app-local"
kv_namespaces = [
  { binding = "ENV_VAR_KV", id = "<LOCAL-STORAGE>", preview_id = "<NOT-USED>" },
]

[[env.local.d1_databases]]
binding = "ENV_VAR_DB"                               # i.e. available in your Worker on env.DB
database_name = "env_var_db"
database_id = "0c770cfa-08d4-4e65-afeb-f989c3a10790" # just used for backups during a local migration

[env.local.vars]
PUBLIC = "this is local public"

# PRODUCTION
[env.production]
name = "env-app-production"
kv_namespaces = [
  { binding = "ENV_VAR_KV", id = "48ea7b7c25b54ce780f5a50fb14bb583", preview_id = "<NOT-USED>" },
]

[[env.production.d1_databases]]
binding = "ENV_VAR_DB"                               # i.e. available in your Worker on env.DB
database_name = "env_var_db"
database_id = "32180390-a2de-458d-90b2-9c49e538b86d"

[env.production.vars]
PUBLIC = "this is PRODUCTION public"
